### DISCUSSION TITLE
How can I link an OIDC Author profile to a Github Author

### DISCUSSION THREAD

**Discussion by HeavyWaterDev** [change-metrics/monocle#1098] [General]
## Connecting OIDC-Generated Profile to GitHub Author

Hello!

I'm currently attempting to link an OIDC-generated profile with an existing GitHub author.

I find myself uncertain about the process of connecting the OIDC account to the corresponding GitHub account. I suspect that I might be using the incorrect AuthProviderUID.

I have attempted digging through the code but am not familiar with the project well enough to figure out myself.

I think I need to put the right UID from the azure tenant here:

```yaml
idents:
  - ident: John Doe
    aliases:
      - github.com/john-doe
      - AuthProviderUID:<Not sure what UID is from the Azure tenant>
```

Any advice would be helpful, 
really cool project!
