### DISCUSSION TITLE
Help with OIDC Authentication

### DISCUSSION THREAD

**Discussion by chinghwa** [change-metrics/monocle#1120] [Q&A]
From the docker and Okta logs, I believe I'm successfully being authenticated however when it redirects to the main page, the authentication window is still shown. How can I debug this further?

docker log:
```
2024-05-21 21:45:07 INFO    Monocle.Main:174: AuthSystemReady {"provider":"okta"}
```

`MONOCLE_OIDC_OKTA_CLIENT_SECRET` is set in `.secrets`.

```
auth:
  auth_provider:
    oidc_client_id: <id>
    oidc_issuer_url: https://<okta_url>/oauth2/default
    oidc_provider_name: okta
    oidc_user_claim: sub
  enforce_auth: true
```
<img width="590" alt="oidc_success1" src="https://github.com/change-metrics/monocle/assets/71664702/011dc557-6d64-4039-b52d-411c41aa01dd">
