### ISSUE TITLE
question: Not indexing past events

### ISSUE THREAD

**Issue by bartelemi** [change-metrics/monocle#1012]
Hi!

I am investigating monocle as a potential tool to track certain aspects of our platform maturity.
I got it up and running locally pretty quickly, but it seems that monocle is not indexing past events, only events that happened when it's actively running.

Here's the config _~/projects/monocle/etc/config.yaml_:

```yaml
---
workspaces:
  - name: tem
    crawlers:
      - name: github-tem-energy
        update_since: "2023-01-01"
        provider:
          github_organization: tem-energy
    projects: []
```

And example screenshot from the web UI:
![image](https://user-images.githubusercontent.com/6844101/215069899-48b6f72c-49e4-40c6-b02c-1f529d6cc3a5.png)

You can see that the data starts on 2023-01-22 and I can ensure you there were plenty of pull-request and commits before that 😄

I wonder if it's just me, some misconfiguration, or that is in fact a desired behaviour? I would imagine that setting the `update_since` in the past would have the effect I desire.
I checked crawler logs for any indication of hitting rate-limit, but that's not the case.
