### ISSUE TITLE
Crawler failed to load when using loop_delay_sec 

### ISSUE THREAD

**Issue by leonid-deriv** [change-metrics/monocle#1085]
define loop_delay_sec, crawler failing during startup 
Maybe I put it in the wrong place?

```YAML
crawlers:
  # Wait one hour between iteration
  loop_delay_sec: 3600
  -  name: xxx
      provider: ...
  - name: yyy
     provider
 
```
