### ISSUE TITLE
GitHub Project LLVM Failing and not indexing

### ISSUE THREAD

**Issue by bigmadkev** [change-metrics/monocle#1093]
With the following config I'm getting a lot of errors and left it to run over night with no data stored.
Using a fine grain token with the settings for private repos as the readme suggests.
```
---
workspaces:
  - name: llvm
    crawlers:
      - name: github-llvm
        provider:
          github_organization: llvm
          github_repositories: 
            - llvm-project
          github_token: GITHUB_TOKEN
        update_since: '2023-10-01'
```

I've attached the logs from the doker containers

[api.log](https://github.com/change-metrics/monocle/files/13623912/api.log)
[crawler.log](https://github.com/change-metrics/monocle/files/13623913/crawler.log)
[elastic.log](https://github.com/change-metrics/monocle/files/13623914/elastic.log)

Any help / pointers really apprecaited.
