### ISSUE TITLE
Docker-compose up gives error on macos M2 - api&crawler doesn't work together

### ISSUE THREAD

**Issue by senolatac** [change-metrics/monocle#1123]
set `etc/config.yaml `like:

```
---
workspaces:
  - name: sa
    crawlers:
      - name: github-sa-cd
        provider:
          github_organization: sa
        update_since: '2021-01-01'
```

and secrets:

```
MONOCLE_ADMIN_TOKEN=admin-token
GITHUB_TOKEN=...
CRAWLERS_API_KEY=custom-api-key-gnhjk-olıuyt-poster-kmlutyr
```

and docker-compose.yaml:
```
version: '3.8'


services:
  api:
    platform: linux/amd64
    command: monocle api
    depends_on:
      elastic:
        condition: service_healthy
    env_file: ".secrets"
    environment:
      MONOCLE_API_PORT: '8080'
      MONOCLE_CONFIG: /etc/monocle/config.yaml
      MONOCLE_ELASTIC_URL: http://elastic:9200
      MONOCLE_PUBLIC_URL: "${COMPOSE_MONOCLE_PUBLIC_URL:-http://localhost:8080}"
      MONOCLE_WEBAPP_PATH: /usr/share/monocle/webapp/
      MONOCLE_WEBAPP_TITLE: "${COMPOSE_MONOCLE_WEBAPP_TITLE:-Monocle}"
    healthcheck:
      retries: 6
      test: "curl --silent --fail localhost:8080/health || exit 1"
      timeout: "60s"
    image: "quay.io/change-metrics/monocle:${COMPOSE_MONOCLE_VERSION:-1.11.1}"
    ports:
      - "${COMPOSE_MONOCLE_API_ADDR:-0.0.0.0}:${COMPOSE_MONOCLE_API_PORT:-8080}:8080"
    #restart: unless-stopped
    volumes:
      - "./etc:/etc/monocle:z"
  crawler:
    platform: linux/amd64
    command: monocle crawler
    depends_on:
      api:
        condition: service_healthy
    env_file: ".secrets"
    environment:
      MONOCLE_CONFIG: /etc/monocle/config.yaml
      MONOCLE_PUBLIC_URL: http://api:8080
    healthcheck:
      retries: 6
      test: "curl --silent --fail localhost:9001/health || exit 1"
      timeout: "60s"
    image: "quay.io/change-metrics/monocle:${COMPOSE_MONOCLE_VERSION:-1.11.1}"
    #restart: unless-stopped
    volumes:
      - "./etc:/etc/monocle:z"

  elastic:
    environment:
      ES_JAVA_OPTS: "-Xms${COMPOSE_ES_XMS:-512m} -Xmx${COMPOSE_ES_XMX:-512m}"
      discovery.type: single-node
    expose:
      - 9200
    healthcheck:
      retries: 6
      test: "curl --silent --fail localhost:9200/_cluster/health || exit 1"
      timeout: "60s"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: cn-mon-elastic
    #restart: unless-stopped
    ulimits:
      nofile:
        hard: 65535
        soft: 65535
    volumes:
      - "./monocle-data/es-data:/usr/share/elasticsearch/data:Z"
```

then `docker compose up`

end api service logs:

```
2024-07-06 09:32:08 INFO    Monocle.Backend.Index:471: Ensure workspace  {"index":"monocle.changes.1.sa"}
2024-07-06T09:32:09.210754636Z 2024-07-06 09:32:08 INFO    Monocle.Backend.Index:462: Ensure schema version {"version":7}
2024-07-06T09:32:09.210878345Z 2024-07-06 09:32:08 INFO    Monocle.Main:195: SystemReady {"workspace":1,"port":8080,"elastic":"http://elastic:9200"}
2024-07-06T09:32:28.168631798Z /bin/monocle: line 3:     8 Killed                  env LD_PRELOAD=/nix/store/l8b6sqp0jq01cyqhpl2kaibymg8hyql1-fakeroot-1.27/lib/libfakeroot.so /nix/store/070hbckd31w72v42pyc748a6hbhxs35k-monocle-1.11.1/bin/monocle $*

```

Killed when `crawler` is trying to up.
