### ISSUE TITLE
[spec] Consolidation of Change data from external task tracker

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#301]
Specification
========

Todo

**Comment by apevec** [comment]
@morucci reviewed from the user perspective 👍🏼

**Comment by TristanCacqueray** [comment]
After working on an initial worker implementation, it seems like the spec could be adjusted for a more efficient workflow. The proposed changes would enable:

- Less configuration, the worker would be stateless
- Less complexicity, the worker would not have to compute the `<change_id>`

### Task summary endpoint

Similarly to the repo or project summary endpoint, a task summary provides the list of task tracker configured for a tenant. The configuration could looks like this:

```yaml
task_trackers:
  - url: bugzilla.redhat.com
    type: bz
    search_expr:
      and:
        - ProductField: "Red Hat Openstack"
        - and:
           - StatusField: "Assigned"
           - CustomField: "ext_bz_bug_map.ext_bz_bug_id"
  - url: api.github.com
    type: gh
```

The returned data could look like this:

```yaml
summary:
  bugzilla.redhat.com:
    tasks: 24
    tasks_open: 8
    tasks_closed: 12
    last_update: 2021-04-08T15:38:00
  api.github.com:
    ...
```

Then the worker would query the configured task trackers to start working.

### Update task summary

The worker would commit a run by updating the task summary end point, effectively logging the last update timestamp so that further runs resume properly.

### Amend change by URL

The worker may not be able to construct the full `<change_id>` when adding metadata, instead the API could accept a simpler change_url to amend a change.

**Comment by morucci** [comment]
Thinking also a bit more about it, yes the spec needs some adjustments.

## The configuration needs a section for the issue tracker crawlers

```
---
tenants:
  - index: <index-name>
    crawler:
      loop_delay: 10
      github_orgs: []
      tasks_tracker_crawlers:
         - name: <crawler-name>
           tasks_updated_since: 2021-01-01T00:00:00
           api_key: <key>
```

Thinking about your proposal @TristanCacqueray to add tracker specific information into the configuration file of Monocle, yes it decreases the complexity about the tracker configuration but it adds complexity in the Monocle configuation file. But the main problem is the search expression that is specific to each issue tracker type. One should be able to write a task tracker crawler for let's say "Monorail: https://bugs.chromium.org/" w/o any prior support into Monocle.

## A new endpoint for a crawler to get the `task_updated_since` date

```
GET /api/0/task_tracker/updated_since_date?index=<index-name>&name=<crawler-name>
Return "2021-01-01T00:00:00"
```

The API returns the default date from the configuration file if no tasks_tracker object found in the EL index. Instead, if some, it returns the most recent task updated date found in the EL index.

## tracker_data properties

```
"tracker_data": {
    "properties": {
        "tracker_name": {"type": "keyword"},
        "last_updated": {"type": "date"},
        "issue_type": {"type": "keyword"},
        "severity": {"type": "keyword"},
        "priority": {"type": "keyword"},
        "score": {"type": "integer"},
        "issue_id": {"type": "keyword"},
        "issue_url": {"type": "keyword"}
        "issue_title": {
            "type": "text",
            "fields": {"keyword": {"type": "keyword", "ignore_above": 8191}},
        },
    }
}
```

Note that for a given change, multiple tracker_data (a tracker_data references a task on a task tracker) can be added. So tracker data must be a list.

## /api/0/amend/changes

As raised by @TristanCacqueray the change_url is used in favor of the change_id that might not be built by a crawler.

```
@authorized (Need to provide an API key to authenticate)
POST /api/0/amend/changes?index=<index-name>&apikey=<apikey>&tracker-name=<name>
[CHANGE,]
CHANGE {
        "id": <string> -> The UUID of the issue on the tack-tracker
        "last_updated": <string>,
        "change_url": <string>,
        "issue_type": <string>,
        "severity": <string>,
        "priority": <string>,
        "score": <int>,
        "issue_id": <string>,
        "issue_url": <string>,
        "issue_title": <string>
}
```

Here two cases for each CHANGE:

- We find a matching change in the EL DB then we insert data in the tracker_data field of the change.
- We cannot find a match in the EL DB then we keep the data into a new doc type called ORPHAN_TRACKER_DATA.

The regular changes crawlers (for Gerrit or Github) must look at ORPHAN_TRACKER_DATA documents if a tracker_data must be included within a new/updated change to be indexed. If it the case the data is included and the ORPHAN_TRACKER_DATA document is deleted.

Keeping orphan tracker_data documents allows to get a more consistent computation of the updated_since date.
W/o this system a new repository appearing into the EL DB might never get tracker_data update.
