### ISSUE TITLE
Add project support

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#329]
For each indices, Monocle must allow to define a list of projects. A project is defined by a repository regexp, branches regexp, excluded authors, releases.

```YAML
tenants:
  - index: openstack
    crawler:
      loop_delay: 600
      gerrit_repositories: []
    projects:
      - name: infra
        repositories-regex: "opendev/system-config|openstack/disskimage-builder"
        branches-regex: "master"
        excluded_authors: "Zuul Bot,Other bot"
        releases:
           - name: Victoria
             from-date: 2020-04-14
             to-date: 2020-10-14
```

This definition can be queried from the Monocle API. The web UI uses that definition to propose to the user a list of projects for a given index. Once a project is selected then the filter fields are set given the project definition.
