### ISSUE TITLE
How can I define user groups? 

### ISSUE THREAD

**Issue by wilau2** [change-metrics/monocle#451]
![image](https://user-images.githubusercontent.com/5473183/124661184-2cdaaa80-de75-11eb-906e-18091b537b19.png)

**Comment by TristanCacqueray** [comment]
The documentation of this feature is missing, in the meantime you can define identity and groups in the index configuration like so:

```yaml
tenants:
  - index: my-index
    idents:
      - ident: Alice Foo
        aliases:
          - github.com/UserName
        groups:
          - group-name
          - other-group-name
      - ident: Bob Bar
        aliases:
          - github.com/BobName
        groups:
          - group-name
```
