### ISSUE TITLE
Board configuration

### ISSUE THREAD

**Issue by TristanCacqueray** [change-metrics/monocle#454]
The goal is to enable the user to configure custom boards.

- Add board configuration: `[(Name, [(ColumnName, Expr)])]`.

```yaml
  board:
    - name: TripleO board
      columns:
        - name: Priority
          query: "score>20"
        - name: Todo
          query: "state:open and updated_at>now-1week"
```

- Add user defined board to the change drop down menu.
