### ISSUE TITLE
Query improvement

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#464]
The goal is to improve the query usage through the web interface. Modifiers such as 'limit' are better handled separately. This is important to enable per page query, for example to combine an author filter along with the global filter. In that situation it's tricky to support modifier in both filters.

- [x] Remove order by and limit from the query language.
- [x] Update the web search bar to include order-by and limit input.
- [x] Add field alias from and to for 'created_at<' and 'created_at>'.
- [x] Add project field.
- [x] Add search alias configuration: [(Name, Expr)].

```yaml
  search_aliases:
    - name: "approved"
      alias: "(approval:Code-Review+2)"
    - name: "sprint-01"
      alias: "from:2021-01-03 to:201-01-24"
```
