### ISSUE TITLE
Github organization crawler do not work with account without a repository list

### ISSUE THREAD

**Issue by byjg** [change-metrics/monocle#741]
I setup the config.yaml with the following settings:

```
---
workspaces:
  - name: demo
    crawlers_api_key: CRAWLERS_API_KEY
    crawlers:
      - name: test
        update_since: '2021-01-01'
        provider:
          github_token: GITHUB_TOKEN
          github_organization: byjg
    projects:
     - name: all
       repository_regex: ".*"
```

And setup my .secrets with:

```
CRAWLERS_API_KEY=redacted
GITHUB_TOKEN=redacted
```

However I am getting the following error:

```
crawler-legacy_1  | 2021-11-23 23:23:24,539 - monocle.main - 140655972263744 - MainThread - INFO - Discovering repositories in byjg ...
crawler-legacy_1  | 2021-11-23 23:23:25,169 - monocle.github.graphql - 140655972263744 - MainThread - INFO - Got rate limit data: remain 4999 resetat 2021-11-24 00:23:23+00:00
crawler-legacy_1  | 2021-11-23 23:23:26,371 - monocle.github.graphql - 140655972263744 - MainThread - ERROR - Errors in response: {'data': {'organization': None}, 'errors': [{'type': 'NOT_FOUND', 'path': ['organization'], 'locations': [{'line': 2, 'column': 11}], 'message': "Could not resolve to an Organization with the login of 'byjg'."}]}
crawler-legacy_1  | Traceback (most recent call last):
crawler-legacy_1  |   File "/usr/local/bin/monocle", line 33, in <module>
crawler-legacy_1  |     sys.exit(load_entry_point('monocle==1.1.0', 'console_scripts', 'monocle')())
crawler-legacy_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-1.1.0-py3.9.egg/monocle/main.py", line 292, in main
crawler-legacy_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-1.1.0-py3.9.egg/monocle/github/organization.py", line 77, in get
crawler-legacy_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-1.1.0-py3.9.egg/monocle/github/organization.py", line 59, in _getPage

```

Do you know if I am doing something wrong?

**Comment by TristanCacqueray** [comment]
It seems like the github crawler currently requires a repository list for regular account, for example:

```yaml
workspaces:
  - name: demo
    crawlers:
      - name: test
        update_since: '2021-01-01'
        provider:
          github_token: GITHUB_TOKEN
          github_organization: byjg
          github_repositories:
            - php-swagger-test
            - migration 
```

I guess the code needs to be adjusted to try fetching the repository list for an account as it is currently using `organization.RepositoriesFetcher` which appears to be incompatible for non organization.
