### ISSUE TITLE
Ignore idents

### ISSUE THREAD

**Issue by asbjornu** [change-metrics/monocle#791]
Is it possible to somehow ignore certain `idents`? I've made 50 lines of configuration for grouping Dependabot, Codecov, Codacy, Mergify, etc., into a `bots` group and would like them all to vanish from all metrics. Is it possible?

Also, the alias grouping does not seem to be working. I have this in my configuration:

```yaml
      - ident: Dependabot
        aliases:
          - dependabot
          - dependabot[bot]
          - dependabot-preview
          - dependabot-preview[bot]
          - github.com/dependabot
```

And still both `Dependabot` and `dependabot-preview` is showing up in the data:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/12283/146099875-53d5e35d-d909-4fda-a2f5-93302bc2f97a.png">

**Comment by TristanCacqueray** [comment]
Hi, I think this would be possible with https://github.com/change-metrics/monocle/issues/522 . Until then, setting `not group:bots` in the query should do the trick.

**Comment by morucci** [comment]
Hi, internally logins are prefixed with the provider domain. So try prefixing all aliases with "github.com/".

**Comment by asbjornu** [comment]
> Hi, I think this would be possible with #522 . Until then, setting `not group:bots` in the query should do the trick.

Thanks, that got rid of `Dependabot`, but `dependabot-preview`, `github-actions`, etc. are still present.

> Hi, internally logins are prefixed with the provider domain. So try prefixing all aliases with "github.com/".

Thanks, @morucci. But prefixing with `github.com/` doesn't seem to have an effect. 😕 

```yaml
    idents:
      - ident: Dependabot
        aliases:
          - github.com/dependabot
          - github.com/dependabot-preview
        groups:
          - bots
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/12283/146177610-b7da25b2-48e3-4d65-815b-fe2f27597fa3.png">
