### ISSUE TITLE
SSL Certificate: Invalid header type 60

### ISSUE THREAD

**Issue by LunaticMuch** [change-metrics/monocle#822]
I am seeing a weird message in my crawler logs

```
crawler_1  | 2022-02-13 09:14:31 Unknown: Network error: 4/7 github.mycomp.com:443/ failed: InternalException 
(HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 60\nFrom:\theader\n\n"))
```

I am using GitHub enterprise, and I am interesting in a single repo which is at URL `https://github.mycomp.com/tech-eng/myrepo`
The config I am using is 

```yaml
workspaces:
  - name: myworkspace
    crawlers:
      - name: mycompany-crawler
        update_since: '2019-01-01'
        provider:
          github_organization: tech-eng
          github_url: https://github.mycomp.com
          github_token: GITHUB_TOKEN
          github_repositories:
            - myepo
```

And the token in the secrets is my valid token. I am wondering if it might be a certificate issue as the ssl certificate is not public, so the container might not be able to validate it. If so, is there any option I could use to accept invalid certificate? or to upload another cert authority?
