### ISSUE TITLE
Is it possible to ignore some authors?

### ISSUE THREAD

**Issue by ipereziriarte** [change-metrics/monocle#849]
Hi!

First of all, thank you for this awesome tool! 

I'm using it on a repo where we use bots in the CI pipeline. I was wondering if it's possible to filter them out (maybe through the yaml file) so they don't pollute the Peers-Strength graph.

I haven't see any reference to that in the docs, but I might be missing something.

Thanks in advance!

**Comment by morucci** [comment]
Hi,

Thanks good to hear that !

Through the query language this is possible to exclude authors: "from:2022-01-24 to:2022-03-24 not (author:github-actions or author:bedevere-bot)"
demo here: https://demo.changemetrics.io/python/peers_strength?q=from%3A2022-01-24+to%3A2022-03-24+not+%28author%3Agithub-actions+or+author%3Abedevere-bot%29+

Through the config file you might be able to use the search aliases:

```
workspaces:
  - name: demo
    search_aliases:
      - name: bots
        alias: '(author:"github-actions" or author:"bedevere-bot")'
```

Then the query could be: "from:2022-01-24 to:2022-03-24 not bots"

And that true it seems that this is not documented. I'll propose a change asap.
Thanks
