### ISSUE TITLE
GitHub Enterprise: ratelimit is optional (can be unlimited)

### ISSUE THREAD

**Issue by jumanjiman** [change-metrics/monocle#958]
Thank you for this project!

I used the Docker image to test it against a private **GHE (GitHub Enterprise)** instance and 
discovered a bug and opportunity for enhancement.

## Expected

https://github.com/change-metrics/monocle/blob/master/src/Lentille/GitHub/RateLimit.hs
should handle the case where GHE admins have disabled rate limits on a GHE instance.

## Actual

When GHE ratelimit is disabled (i.e., _unlimited_ ratelimit),
GitHub crawler treats `null` ratelimit as an error and
therefore fails to crawl org data.

### log output

This was the relevant line in `docker-compose logs`, and
I inserted line breaks here for readability:

```
crawler_1  | 2022-09-28 14:11:30 WARNING Macroscope.Main:283: 
Skipping due to an unexpected exception 
{"index":"monocle-test","crawler":"GHE","err":"Invalid response: GetRateLimit {rateLimit = Nothing}
CallStack (from HasCallStack):
  error, called at src/Relude/Debug.hs:289:11 in relude-1.1.0.0-IXqsgVzL4PV6JByrFzskHM:Relude.Debug
  error, called at src/Lentille/GitHub/RateLimit.hs:43:16 in monocle-0.1.7.0-2VW3DhZvn5r33orcK7VHBU:Lentille.GitHub.RateLimit"}
```

### config

```yaml
---
# https://github.com/change-metrics/monocle#configuration-file
workspaces:
    - name: monocle-test
      crawlers:
          - name: GHE
            update_since: '2021-01-01'
            provider:
                github_url: https://ghe.example.com/api/graphql  # redacted
                github_organization: internalorg  # redacted
```

## Reproducer

I wrote a trivial bash script to demonstrate actual responses from our GHE instance.

### reproducer script output

```
Get ratelimit with REST API v3
{
  "message": "Rate limiting is not enabled.",
  "documentation_url": "https://docs.github.com/enterprise/3.6/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user"
}
HTTP response code 404

Get ratelimit with GraphQL API
{"data":{"rateLimit":null}}
HTTP response code 200
```

### reproducer script

```bash
#!/usr/bin/env bash
set -eEu
set -o pipefail

# Use env var to hide corporate namespace.
GITHUB_BASE_URL="${GITHUB_BASE_URL:-https://ghe.example.com}"

echo 'Get ratelimit with REST API v3'
curl \
    -H 'Accept: application/vnd.github+json' \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    --write-out 'HTTP response code %{http_code}' \
    "${GITHUB_BASE_URL}/api/v3/rate_limit"

echo
echo

echo 'Get ratelimit with GraphQL API'
curl \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -X POST \
    -d '{"query": "query GetRateLimit  {rateLimit { used remaining resetAt } }"' \
     --write-out 'HTTP response code %{http_code}' \
   "${GITHUB_BASE_URL}/api/graphql"
```

### GraphiQL screenshot

as a confirmation of the reproducer script and output:

![image](https://user-images.githubusercontent.com/332496/192804139-cacaa7ca-2858-4b58-80b5-4b64d6eb1cfb.png)

## Possible related issues

- No details in the issue, but it sounds like a user config error (omitted `/api/graphql` in URL:
  https://github.com/change-metrics/monocle/issues/876
